pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-argument: true
  params: count=countSql







  #  schema:
#       - classpath:sql/department.sql
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#       - classpath:sql/employee.sql


thymeleaf:
  cache: false

#  content-type: text/html
  mode: HTML5
